{
 "title": "Massa Node",
 "tags": [
  "massa",
  "node"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Block Production Rate",
   "targets": [
    {
     "expr": "rate(massa_getadd_cycle_block_produit[5m])",
     "legendFormat": "Blocks/min"
    }
   ]
  },
  {
   "title": "Block Production Success Rate",
   "targets": [
    {
     "expr": "sum(massa_getadd_cycle_block_produit) / (sum(massa_getadd_cycle_block_produit) + sum(massa_getadd_cycle_block_echoue)) * 100",
     "legendFormat": "Success %"
    }
   ]
  },
  {
   "title": "Wallet Balance",
   "targets": [
    {
     "expr": "massa_getadd_roll_final_balance",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "Balance Change",
   "targets": [
    {
     "expr": "delta(massa_getadd_roll_final_balance[24h])",
     "legendFormat": "24h change"
    }
   ]
  },
  {
   "title": "Staking Rewards",
   "targets": [
    {
     "expr": "176256 * (sum(massa_getadd_roll_final_roll) / sum(rolls))",
     "legendFormat": "Daily rewards"
    }
   ]
  },
  { "title": "Massa network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active cycle",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "massa_getstatus_network_stats_current_cycle",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Active cursor period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_cursor_period" }
   ]
  },
  {
   "title": "Active cursor thread",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_cursor_thread" }
   ]
  },
  {
   "title": "Total number of rolls",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rolls" }
   ]
  },
  {
   "title": "Stakers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stakers" }
   ]
  },
  { "title": "My node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Daily ($MASSA)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "176256 * sum(massa_getadd_roll_final_roll) / sum(rolls)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APR (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(176256 * (sum(massa_getadd_roll_final_roll) / sum(rolls)) * 365) / sum(massa_getadd_roll_final_roll)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "APY (%)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "(((1+($B/100/$C))**$C)-1)*100", "type": "math" }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "massa_getstatus_network_stats_in_connection_count",
     "legendFormat": "IN"
    },
    {
     "expr": "massa_getstatus_network_stats_out_connection_count",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "massa_getstatus_network_stats_known_peer_count",
     "legendFormat": "Known peer"
    },
    {
     "expr": "massa_getstatus_network_stats_banned_peer_count",
     "legendFormat": "Banned peer"
    }
   ]
  },
  {
   "title": "Active rolls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(massa_getadd_roll_final_roll)",
     "legendFormat": "Rolls"
    }
   ]
  },
  {
   "title": "$MASSA balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "massa_getadd_roll_final_balance",
     "legendFormat": "$MASSA"
    }
   ]
  },
  {
   "title": "Roll Candidate vs Final",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "massa_getadd_roll_candidate_roll",
     "legendFormat": "Candidate"
    },
    { "expr": "massa_getadd_roll_final_roll", "legendFormat": "Final" }
   ]
  },
  {
   "title": "$MASSA Candidate vs Final",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "massa_getadd_roll_candidate_balance",
     "legendFormat": "Candidate"
    },
    {
     "expr": "massa_getadd_roll_final_balance",
     "legendFormat": "Final"
    }
   ]
  },
  {
   "title": "$MASSA Candidate and final",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "massa_getadd_roll_final_balance",
     "legendFormat": "Final balance"
    },
    {
     "expr": "massa_getadd_roll_candidate_balance",
     "legendFormat": "Candidate balance"
    }
   ]
  },
  {
   "title": "Average blocks mined (7 cycle)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "avg(massa_getadd_cycle_block_produit)",
     "legendFormat": "Blocks mined (AVG)"
    }
   ]
  },
  {
   "title": "Average blocks failed (7 cycle)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "avg by() (massa_getadd_cycle_block_echoue)",
     "legendFormat": "Blocks failed (AVG)"
    }
   ]
  },
  {
   "title": "Rolls Candidate and Final",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    { "expr": "massa_getadd_roll_final_roll", "legendFormat": "FInal Rolls" },
    {
     "expr": "massa_getadd_roll_candidate_roll",
     "legendFormat": "Candidate Rolls"
    }
   ]
  },
  {
   "title": "Production block per cycle",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum by(cycle) (massa_getadd_cycle_block_produit)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}