{
 "title": "Powerloom Lite Node Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "api_url",
    "label": "API URL",
    "query": {
     "query": "label_values({__name__=~\".*_epochId$\"},api_url)"
    }
   },
   {
    "name": "node_names",
    "label": "Node Names",
    "query": {
     "query": "label_values({__name__=~\".*_epochId$\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Non-OK nodes",
   "type": "stat",
   "description": "Number of nodes that likely require attention",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (powerloom_status{status!=\"OK\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status)(powerloom_status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Highest Epoch ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(sum by(node) (powerloom_epochId))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Epoch IDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum by (node) (powerloom_epochId)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Nodes summary",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (node, api_url, status) (powerloom_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (powerloom_epochId)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Node $node_names", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "node_names" },
  {
   "title": "Latest EpochID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "powerloom_epochId{node=\"$node_names\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (powerloom_status{node=\"$node_names\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "API URL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api_url) (powerloom_epochId{node=\"$node_names\"})",
     "legendFormat": "{{api_url}}"
    }
   ]
  },
  {
   "title": "Powerloom EpochID",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "powerloom_epochId{node=\"$node_names\"}",
     "legendFormat": "epochId"
    }
   ]
  }
 ]
}